// ACTION's

// User
export const UserActions = {
    CREATE_USER: "CREATE_USER",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    READ_USERS: "READ_USERS",
    READ_USERS_SUCCESS: "READ_USERS_SUCCESS",
    READ_USER: "READ_USER",
    TOGGLE_USER_FORM: "TOGGLE_USER_FORM",
};
// Team
export const TeamActions = {
    CREATE_TEAM: "CREATE_TEAM",
    CREATE_TEAM_SUCCESS: "CREATE_TEAM_SUCCESS",
    READ_TEAMS: "READ_TEAMS",
    READ_TEAMS_SUCCESS: "READ_TEAMS_SUCCESS",
    TOGGLE_TEAM_FORM: "TOGGLE_TEAM_FORM",
    TOGGLE_TEAM_TODO : "TOGGLE_TEAM_TODO",
    TOGGLE_TODO_FORM : "TOGGLE_TODO_FORM",
};
export const TodoActions = {
    ADD_TODO : "ADD_TODO",
    DELETE_TODO : "DELETE_TODO",
    ADD_TODO_SUCCESS : "ADD_TODO_SUCCESS",
    DELETE_TODO_SUCCESS : "DELETE_TODO_SUCCESS",
};
// Dashboard
export const DashboardActions = {
    READ_TASKS : "READ_TASKS",
    READ_TASKS_SUCCESS : "READ_TASKS_SUCCESS",
    READ_TASK : "READ_TASK",
    READ_TASK_SUCCESS : "READ_TASK_SUCCESS",
    CREATE_TASK: "CREATE_TASK",
    CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
    CHANGE_VIEW: "CHANGE_VIEW",
    CHANGE_MONTH: "CHANGE_MONTH",
    CHANGE_DATE: "CHANGE_DATE",
    TOGGLE_TASK_FORM: "TOGGLE_TASK_FORM",
    TOGGLE_TASK_NOTES: "TOGGLE_TASK_NOTES",
    TOGGLE_TASK_OPTS: "TOGGLE_TASK_OPTS",
};
// Navbar
export const NavbarActions = {
    TOGGLE_DRAW : "TOGGLE_DRAW",
};